server:
  port: 9291
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:example
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  
  application:
    name: AMAZONE-SHOPPING
 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
 