server:
  port: 8989
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost      
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: amazon-shopping
        uri: lb://AMAZONE-SHOPPING
        predicates:
          - Path=/order/**
      - id: payment-service
        uri: lb://PAYMENT-SERVICE
        predicates:
          - Path=/payment/**

  main:
    web-application-type: reactive