server:
  port: 9292
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  
  application:
    name: PAYMENT-SERVICE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost